### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by GinBlades** [GinBlades/Slog#1]
- [ ] Enable other TinyMCE menu options (lists, HTML view, links, etc)
- [ ] SSL
- [ ] Users or Admins can change passwords
- [ ] Oauth Providers, Google, Facebook, and Twitter
- [ ] Caching
- [ ] Better comment protection
- [ ] Real styling
- [ ] RSS Feed
- [x] Signed in users get name with comment.
- [x] Admins and Moderators can approve comments.
- [x] Blog-like URLs
- [x] TinyMCE
- [x] Picture Upload
- [x] Add author role for guest authors.
- [x] Only admins or authors can post
- [x] Admins can manage roles

**Comment by GinBlades** [comment]
[Save a File to Stream](http://stackoverflow.com/questions/411592/how-do-i-save-a-stream-to-a-file-in-c)

    using (var fileStream = File.Create("C:\\Path\\To\\File")) {
        myOtherObject.InputStream.Seek(0, SeekOrigin.Begin);
        myOtherObject.InputStream.CopyTo(fileStream);
    }

**Comment by GinBlades** [comment]
[Negative Captcha](https://github.com/subwindow/negative-captcha) for Comments

**Comment by GinBlades** [comment]
RSS/Atom feeds can be generated [using WCF's SyndicationFeed](http://rehansaeed.com/building-rssatom-feeds-for-asp-net-mvc/), but it isn't available in .NET Core. It will probably need to be built from XML.
